### ISSUE TITLE
왜 gif로 구워요

### ISSUE THREAD

**Issue by xnuk** [ruby3141/readme-assets#1]
77cfa13ef76cec1eb3e259def51d1ea296563659

깃헙 이제 동영상 업로드 될 걸요 `ffmpeg -i preview.gif preview.mp4` 하시면 됨

https://github.com/ruby3141/readme-assets/assets/3071003/f8b265ac-c3ca-4fdd-be18-1949562d3a5b

**Comment by xnuk** [comment]
yuv444p라서 파폭에서 재생 안 되네 그럼 이렇게

`ffmpeg -i preview.gif -pix_fmt yuv420p -vf 'crop=floor(iw/2)*2:floor(ih/2)*2' preview.mp4`


https://github.com/ruby3141/readme-assets/assets/3071003/2562e5bb-c513-49d8-9f13-be5e71122946

**Comment by ruby3141** [comment]
mp4가 되는군요. 처음 알았습니다.
근데 그냥 아이캐치 용도로 자동 재생되는 걸 염두하고 넣은 영상이라 mp4는 안 맞을 것 같습니다.

잠깐 찾아봤는데 animated webp로 다시 굽는 게 나을 것 같긴 하네요.

**Comment by xnuk** [comment]
그럴 수도 잇고

**Comment by xnuk** [comment]
근데 자동재생 될 걸요 아마 (불확실함)

**Comment by ruby3141** [comment]
일단 몇 가지 대안 후보를 놓고 건드려보고 있는데, avif가 용량 면에서 압도적이긴 하네요(webp의 16%까지 용량이 줄어듦)
디코딩하는 쪽을 고려를 안 하면 이 쪽이 괜찮을 것 같긴 한데...

**Comment by ruby3141** [comment]
avif로 구웠습니다
다른 데서는 raw=true 안 넣어도 잘 되더니 이상하게 comment에서는 없으면 안 나오네요. 딱히 문제인 건 아닌데...
![Preview](https://github.com/ruby3141/readme-assets/blob/main/DJMAXPlus/preview.avif?raw=true)

**Comment by xnuk** [comment]
와 결혼해
